[[redirects]]
  from = "/api/proxy/*"
  to = "https://boardgamegeek.com/xmlapi2/:splat"
  status = 200
  force = true
  headers = { X-From = "Netlify" }
  
  [[redirects]]
  from = "/api/proxy/xmlapi/*"
  to = "https://boardgamegeek.com/xmlapi/:splat"
  status = 200
  force = true
  headers = { X-From = "Netlify" }

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
